export const surahNames = [
  { id: 1, englishName: "Al-Fatiha", arabicName: "الفاتحة" },
  { id: 2, englishName: "Al-Baqarah", arabicName: "البقرة" },
  { id: 3, englishName: "Al-Imran", arabicName: "آل عمران" },
  { id: 4, englishName: "An-Nisa", arabicName: "النساء" },
  { id: 5, englishName: "Al-Ma'idah", arabicName: "المائدة" },
  { id: 6, englishName: "Al-An'am", arabicName: "الأنعام" },
  { id: 7, englishName: "Al-A'raf", arabicName: "الأعراف" },
  { id: 8, englishName: "Al-Anfal", arabicName: "الأنفال" },
  { id: 9, englishName: "At-Tawbah", arabicName: "التوبة" },
  { id: 10, englishName: "Yunus", arabicName: "يونس" },
  { id: 11, englishName: "Hud", arabicName: "هود" },
  { id: 12, englishName: "Yusuf", arabicName: "يوسف" },
  { id: 13, englishName: "Ar-Ra'd", arabicName: "الرعد" },
  { id: 14, englishName: "Ibrahim", arabicName: "إبراهيم" },
  { id: 15, englishName: "Al-Hijr", arabicName: "الحجر" },
  { id: 16, englishName: "An-Nahl", arabicName: "النحل" },
  { id: 17, englishName: "Al-Isra", arabicName: "الإسراء" },
  { id: 18, englishName: "Al-Kahf", arabicName: "الكهف" },
  { id: 19, englishName: "Maryam", arabicName: "مريم" },
  { id: 20, englishName: "Ta-Ha", arabicName: "طه" },
  { id: 21, englishName: "Al-Anbiya", arabicName: "الأنبياء" },
  { id: 22, englishName: "Al-Hajj", arabicName: "الحج" },
  { id: 23, englishName: "Al-Mu'minun", arabicName: "المؤمنون" },
  { id: 24, englishName: "An-Nur", arabicName: "النور" },
  { id: 25, englishName: "Al-Furqan", arabicName: "الفرقان" },
  { id: 26, englishName: "Ash-Shu'ara", arabicName: "الشعراء" },
  { id: 27, englishName: "An-Naml", arabicName: "النمل" },
  { id: 28, englishName: "Al-Qasas", arabicName: "القصص" },
  { id: 29, englishName: "Al-Ankabut", arabicName: "العنكبوت" },
  { id: 30, englishName: "Ar-Rum", arabicName: "الروم" },
  { id: 31, englishName: "Luqman", arabicName: "لقمان" },
  { id: 32, englishName: "As-Sajda", arabicName: "السجدة" },
  { id: 33, englishName: "Al-Ahzab", arabicName: "الأحزاب" },
  { id: 34, englishName: "Saba", arabicName: "سبأ" },
  { id: 35, englishName: "Fatir", arabicName: "فاطر" },
  { id: 36, englishName: "Ya-Sin", arabicName: "يس" },
  { id: 37, englishName: "As-Saffat", arabicName: "الصافات" },
  { id: 38, englishName: "Sad", arabicName: "ص" },
  { id: 39, englishName: "Az-Zumar", arabicName: "الزمر" },
  { id: 40, englishName: "Ghafir", arabicName: "غافر" },
  { id: 41, englishName: "Fussilat", arabicName: "فصلت" },
  { id: 42, englishName: "Ash-Shura", arabicName: "الشورى" },
  { id: 43, englishName: "Az-Zukhruf", arabicName: "الزخرف" },
  { id: 44, englishName: "Ad-Dukhan", arabicName: "الدخان" },
  { id: 45, englishName: "Al-Jathiyah", arabicName: "الجاثية" },
  { id: 46, englishName: "Al-Ahqaf", arabicName: "الأحقاف" },
  { id: 47, englishName: "Muhammad", arabicName: "محمد" },
  { id: 48, englishName: "Al-Fath", arabicName: "الفتح" },
  { id: 49, englishName: "Al-Hujurat", arabicName: "الحجرات" },
  { id: 50, englishName: "Qaf", arabicName: "ق" },
  { id: 51, englishName: "Adh-Dhariyat", arabicName: "الذاريات" },
  { id: 52, englishName: "At-Tur", arabicName: "الطور" },
  { id: 53, englishName: "An-Najm", arabicName: "النجم" },
  { id: 54, englishName: "Al-Qamar", arabicName: "القمر" },
  { id: 55, englishName: "Ar-Rahman", arabicName: "الرحمن" },
  { id: 56, englishName: "Al-Waqi'ah", arabicName: "الواقع " },
  { id: 57, englishName: "Al-Hadid", arabicName: "الحديد" },
  { id: 58, englishName: "Al-Mujadila", arabicName: "المجادلة" },
  { id: 59, englishName: "Al-Hashr", arabicName: "الحشر" },
  { id: 60, englishName: "Al-Mumtahanah", arabicName: "الممتحنة" },
  { id: 61, englishName: "As-Saff", arabicName: "الصف" },
  { id: 62, englishName: "Al-Jumu'ah", arabicName: "الجمعة" },
  { id: 63, englishName: "Al-Munafiqun", arabicName: "المنافقون" },
  { id: 64, englishName: "At-Taghabun", arabicName: "التغابن" },
  { id: 65, englishName: "At-Talaq", arabicName: "الطلاق" },
  { id: 66, englishName: "At-Tahrim", arabicName: "التحريم" },
  { id: 67, englishName: "Al-Mulk", arabicName: "الملك" },
  { id: 68, englishName: "Al-Qalam", arabicName: "القلم" },
  { id: 69, englishName: "Al-Haqqah", arabicName: "الحاقة" },
  { id: 70, englishName: "Al-Ma'arij", arabicName: "المعارج" },
  { id: 71, englishName: "Nuh", arabicName: "نوح" },
  { id: 72, englishName: "Al-Jinn", arabicName: "الجن" },
  { id: 73, englishName: "Al-Muzzammil", arabicName: "المزمل" },
  { id: 74, englishName: "Al-Muddathir", arabicName: "المدثر" },
  { id: 75, englishName: "Al-Qiyamah", arabicName: "القيامة" },
  { id: 76, englishName: "Al-Insan", arabicName: "الانسان" },
  { id: 77, englishName: "Al-Mursalat", arabicName: "المرسلات" },
  { id: 78, englishName: "An-Naba", arabicName: "النبأ" },
  { id: 79, englishName: "An-Nazi'at", arabicName: "النازعات" },
  { id: 80, englishName: "'Abasa", arabicName: "عبس" },
  { id: 81, englishName: "At-Takwir", arabicName: "التكوير" },
  { id: 82, englishName: "Al-Infitar", arabicName: "الإنفطار" },
  { id: 83, englishName: "Al-Mutaffifin", arabicName: "المطففين" },
  { id: 84, englishName: "Al-Inshiqaq", arabicName: "الإنشقاق" },
  { id: 85, englishName: "Al-Buruj", arabicName: "البروج" },
  { id: 86, englishName: "At-Tariq", arabicName: "الطارق" },
  { id: 87, englishName: "Al-A'la", arabicName: "الأعلى" },
  { id: 88, englishName: "Al-Ghashiyah", arabicName: "الغاشية" },
  { id: 89, englishName: "Al-Fajr", arabicName: "الفجر" },
  { id: 90, englishName: "Al-Balad", arabicName: "البلد" },
  { id: 91, englishName: "Ash-Shams", arabicName: "الشمس" },
  { id: 92, englishName: "Al-Lail", arabicName: "الليل" },
  { id: 93, englishName: "Ad-Duha", arabicName: "الضحى" },
  { id: 94, englishName: "Ash-Sharh", arabicName: "ال شرح" },
  { id: 95, englishName: "At-Tin", arabicName: "التين" },
  { id: 96, englishName: "Al-Alaq", arabicName: "العلق" },
  { id: 97, englishName: "Al-Qadr", arabicName: "القدر" },
  { id: 98, englishName: "Al-Bayyinah", arabicName: "البينة" },
  { id: 99, englishName: "Az-Zalzalah", arabicName: "الزلزلة" },
  { id: 100, englishName: "Al-Adiyat", arabicName: "العاديات" },
  { id: 101, englishName: "Al-Qari'ah", arabicName: "القارعة" },
  { id: 102, englishName: "At-Takathur", arabicName: "التكاثر" },
  { id: 103, englishName: "Al-Asr", arabicName: "العصر" },
  { id: 104, englishName: "Al-Humazah", arabicName: "الهمزة" },
  { id: 105, englishName: "Al-Fil", arabicName: "الفيل" },
  { id: 106, englishName: "Quraish", arabicName: "قريش" },
  { id: 107, englishName: "Al-Ma'un", arabicName: "الماعون" },
  { id: 108, englishName: "Al-Kawthar", arabicName: "الكوثر" },
  { id: 109, englishName: "Al-Kafirun", arabicName: "الكافرون" },
  { id: 110, englishName: "An-Nasr", arabicName: "النصر" },
  { id: 111, englishName: "Al-Masad", arabicName: "المسد" },
  { id: 112, englishName: "Al-Ikhlas", arabicName: "الإخلاص" },
  { id: 113, englishName: "Al-Falaq", arabicName: "الفلق" },
  { id: 114, englishName: "An-Nas", arabicName: "الناس" },
];

export const surahDetails = [
  {
    id: 1,
    name: "Al-Fatiha",
    revelationType: "Meccan",
    totalVerses: 7,
    placeOfRevelation: "Mecca",
  },
  {
    id: 2,
    name: "Al-Baqarah",
    revelationType: "Medinan",
    totalVerses: 286,
    placeOfRevelation: "Medina",
  },
  {
    id: 3,
    name: "Al-Imran",
    revelationType: "Medinan",
    totalVerses: 200,
    placeOfRevelation: "Medina",
  },
  {
    id: 4,
    name: "An-Nisa",
    revelationType: "Medinan",
    totalVerses: 176,
    placeOfRevelation: "Medina",
  },
  {
    id: 5,
    name: "Al-Ma'idah",
    revelationType: "Medinan",
    totalVerses: 120,
    placeOfRevelation: "Medina",
  },
  {
    id: 6,
    name: "Al-An'am",
    revelationType: "Meccan",
    totalVerses: 165,
    placeOfRevelation: "Mecca",
  },
  {
    id: 7,
    name: "Al-A'raf",
    revelationType: "Meccan",
    totalVerses: 206,
    placeOfRevelation: "Mecca",
  },
  {
    id: 8,
    name: "Al-Anfal",
    revelationType: "Medinan",
    totalVerses: 75,
    placeOfRevelation: "Medina",
  },
  {
    id: 9,
    name: "At-Tawbah",
    revelationType: "Medinan",
    totalVerses: 129,
    placeOfRevelation: "Medina",
  },
  {
    id: 10,
    name: "Yunus",
    revelationType: "Meccan",
    totalVerses: 109,
    placeOfRevelation: "Mecca",
  },
  {
    id: 11,
    name: "Hud",
    revelationType: "Meccan",
    totalVerses: 123,
    placeOfRevelation: "Mecca",
  },
  {
    id: 12,
    name: "Yusuf",
    revelationType: "Meccan",
    totalVerses: 111,
    placeOfRevelation: "Mecca",
  },
  {
    id: 13,
    name: "Ar-Ra'd",
    revelationType: "Meccan",
    totalVerses: 43,
    placeOfRevelation: "Mecca",
  },
  {
    id: 14,
    name: "Ibrahim",
    revelationType: "Meccan",
    totalVerses: 52,
    placeOfRevelation: "Mecca",
  },
  {
    id: 15,
    name: "Al-Hijr",
    revelationType: "Meccan",
    totalVerses: 99,
    placeOfRevelation: "Mecca",
  },
  {
    id: 16,
    name: "An-Nahl",
    revelationType: "Meccan",
    totalVerses: 128,
    placeOfRevelation: "Mecca",
  },
  {
    id: 17,
    name: "Al-Isra",
    revelationType: "Meccan",
    totalVerses: 111,
    placeOfRevelation: "Mecca",
  },
  {
    id: 18,
    name: "Al-Kahf",
    revelationType: "Meccan",
    totalVerses: 110,
    placeOfRevelation: "Mecca",
  },
  {
    id: 19,
    name: "Maryam",
    revelationType: "Meccan",
    totalVerses: 98,
    placeOfRevelation: "Mecca",
  },
  {
    id: 20,
    name: "Ta-Ha",
    revelationType: "Meccan",
    totalVerses: 135,
    placeOfRevelation: "Mecca",
  },
  {
    id: 21,
    name: "Al-Anbiya",
    revelationType: "Meccan",
    totalVerses: 112,
    placeOfRevelation: "Mecca",
  },
  {
    id: 22,
    name: "Al-Hajj",
    revelationType: "Medinan",
    totalVerses: 78,
    placeOfRevelation: "Medina",
  },
  {
    id: 23,
    name: "Al-Mu'minun",
    revelationType: "Meccan",
    totalVerses: 118,
    placeOfRevelation: "Mecca",
  },
  {
    id: 24,
    name: "An-Nur",
    revelationType: "Medinan",
    totalVerses: 64,
    placeOfRevelation: "Medina",
  },
  {
    id: 25,
    name: "Al-Furqan",
    revelationType: "Meccan",
    totalVerses: 77,
    placeOfRevelation: "Mecca",
  },
  {
    id: 26,
    name: "Ash-Shu'ara",
    revelationType: "Meccan",
    totalVerses: 227,
    placeOfRevelation: "Mecca",
  },
  {
    id: 27,
    name: "An-Naml",
    revelationType: "Meccan",
    totalVerses: 93,
    placeOfRevelation: "Mecca",
  },
  {
    id: 28,
    name: "Al-Qasas",
    revelationType: "Meccan",
    totalVerses: 88,
    placeOfRevelation: "Mecca",
  },
  {
    id: 29,
    name: "Al-Ankabut",
    revelationType: "Meccan",
    totalVerses: 69,
    placeOfRevelation: "Mecca",
  },
  {
    id: 30,
    name: "Ar-Rum",
    revelationType: "Meccan",
    totalVerses: 60,
    placeOfRevelation: "Mecca",
  },
  {
    id: 31,
    name: "Luqman",
    revelationType: "Meccan",
    totalVerses: 34,
    placeOfRevelation: "Mecca",
  },
  {
    id: 32,
    name: "As-Sajda",
    revelationType: "Meccan",
    totalVerses: 30,
    placeOfRevelation: "Mecca",
  },
  {
    id: 33,
    name: "Al-Ahzab",
    revelationType: "Medinan",
    totalVerses: 73,
    placeOfRevelation: "Medina",
  },
  {
    id: 34,
    name: "Saba",
    revelationType: "Meccan",
    totalVerses: 54,
    placeOfRevelation: "Mecca",
  },
  {
    id: 35,
    name: "Fatir",
    revelationType: "Meccan",
    totalVerses: 45,
    placeOfRevelation: "Mecca",
  },
  {
    id: 36,
    name: "Ya-Sin",
    revelationType: "Meccan",
    totalVerses: 83,
    placeOfRevelation: "Mecca",
  },
  {
    id: 37,
    name: "As-Saffat",
    revelationType: "Meccan",
    totalVerses: 182,
    placeOfRevelation: "Mecca",
  },
  {
    id: 38,
    name: "Sad",
    revelationType: " Meccan",
    totalVerses: 88,
    placeOfRevelation: "Mecca",
  },
  {
    id: 39,
    name: "Az-Zumar",
    revelationType: "Meccan",
    totalVerses: 75,
    placeOfRevelation: "Mecca",
  },
  {
    id: 40,
    name: "Ghafir",
    revelationType: "Meccan",
    totalVerses: 85,
    placeOfRevelation: "Mecca",
  },
  {
    id: 41,
    name: "Fussilat",
    revelationType: "Meccan",
    totalVerses: 54,
    placeOfRevelation: "Mecca",
  },
  {
    id: 42,
    name: "Ash-Shura",
    revelationType: "Meccan",
    totalVerses: 53,
    placeOfRevelation: "Mecca",
  },
  {
    id: 43,
    name: "Az-Zukhruf",
    revelationType: "Meccan",
    totalVerses: 89,
    placeOfRevelation: "Mecca",
  },
  {
    id: 44,
    name: "Ad-Dukhan",
    revelationType: "Meccan",
    totalVerses: 59,
    placeOfRevelation: "Mecca",
  },
  {
    id: 45,
    name: "Al-Jathiyah",
    revelationType: "Meccan",
    totalVerses: 37,
    placeOfRevelation: "Mecca",
  },
  {
    id: 46,
    name: "Al-Ahqaf",
    revelationType: "Meccan",
    totalVerses: 35,
    placeOfRevelation: "Mecca",
  },
  {
    id: 47,
    name: "Muhammad",
    revelationType: "Medinan",
    totalVerses: 38,
    placeOfRevelation: "Medina",
  },
  {
    id: 48,
    name: "Al-Fath",
    revelationType: "Medinan",
    totalVerses: 29,
    placeOfRevelation: "Medina",
  },
  {
    id: 49,
    name: "Al-Hujurat",
    revelationType: "Medinan",
    totalVerses: 18,
    placeOfRevelation: "Medina",
  },
  {
    id: 50,
    name: "Qaf",
    revelationType: "Meccan",
    totalVerses: 45,
    placeOfRevelation: "Mecca",
  },
  {
    id: 51,
    name: "Adh-Dhariyat",
    revelationType: "Meccan",
    totalVerses: 60,
    placeOfRevelation: "Mecca",
  },
  {
    id: 52,
    name: "At-Tur",
    revelationType: "Meccan",
    totalVerses: 49,
    placeOfRevelation: "Mecca",
  },
  {
    id: 53,
    name: "An-Najm",
    revelationType: "Meccan",
    totalVerses: 62,
    placeOfRevelation: "Mecca",
  },
  {
    id: 54,
    name: "Al-Qamar",
    revelationType: "Meccan",
    totalVerses: 55,
    placeOfRevelation: "Mecca",
  },
  {
    id: 55,
    name: "Ar-Rahman",
    revelationType: "Medinan",
    totalVerses: 78,
    placeOfRevelation: "Medina",
  },
  {
    id: 56,
    name: "Al-Waqi'ah",
    revelationType: "Meccan",
    totalVerses: 96,
    placeOfRevelation: "Mecca",
  },
  {
    id: 57,
    name: "Al-Hadid",
    revelationType: "Medinan",
    totalVerses: 29,
    placeOfRevelation: "Medina",
  },
  {
    id: 58,
    name: "Al-Mujadila",
    revelationType: "Medinan",
    totalVerses: 22,
    placeOfRevelation: "Medina",
  },
  {
    id: 59,
    name: "Al-Hashr",
    revelationType: "Medinan",
    totalVerses: 24,
    placeOfRevelation: "Medina",
  },
  {
    id: 60,
    name: "Al-Mumtahanah",
    revelationType: "Medinan",
    totalVerses: 13,
    placeOfRevelation: "Medina",
  },
  {
    id: 61,
    name: "As-Saff",
    revelationType: "Medinan",
    totalVerses: 14,
    placeOfRevelation: "Medina",
  },
  {
    id: 62,
    name: "Al-Jumu'ah",
    revelationType: "Medinan",
    totalVerses: 11,
    placeOfRevelation: "Medina",
  },
  {
    id: 63,
    name: "Al-Munafiqun",
    revelationType: "Medinan",
    totalVerses: 11,
    placeOfRevelation: "Medina",
  },
  {
    id: 64,
    name: "At-Taghabun",
    revelationType: "Medinan",
    totalVerses: 18,
    placeOfRevelation: "Medina",
  },
  {
    id: 65,
    name: "At-Talaq",
    revelationType: "Medinan",
    totalVerses: 12,
    placeOfRevelation: "Medina",
  },
  {
    id: 66,
    name: "At-Tahrim",
    revelationType: "Medinan",
    totalVerses: 12,
    placeOfRevelation: "Medina",
  },
  {
    id: 67,
    name: "Al-Mulk",
    revelationType: "Meccan",
    totalVerses: 30,
    placeOfRevelation: "Mecca",
  },
  {
    id: 68,
    name: "Al-Qalam",
    revelationType: "Meccan",
    totalVerses: 52,
    placeOfRevelation: "Mecca",
  },
  {
    id: 69,
    name: "Al-Haqqah",
    revelationType: "Meccan",
    totalVerses: 52,
    placeOfRevelation: "Mecca",
  },
  {
    id: 70,
    name: "Al-Ma'arij",
    revelationType: "Meccan",
    totalVerses: 44,
    placeOfRevelation: "Mecca",
  },
  {
    id: 71,
    name: "Nuh",
    revelationType: "Meccan",
    totalVerses: 28,
    placeOfRevelation: "Mecca",
  },
  {
    id: 72,
    name: "Al-Jinn",
    revelationType: "Meccan",
    totalVerses: 28,
    placeOfRevelation: "Mecca",
  },
  {
    id: 73,
    name: "Al-Muzzammil",
    revelationType: "Meccan",
    totalVerses: 20,
    placeOfRevelation: "Mecca",
  },
  {
    id: 74,
    name: "Al-Muddathir",
    revelationType: "Meccan",
    totalVerses: 56,
    placeOfRevelation: "Mecca",
  },
  {
    id: 75,
    name: "Al-Qiyamah",
    revelationType: "Meccan",
    totalVerses: 40,
    placeOfRevelation: "Mecca",
  },
  {
    id: 76,
    name: "Al-Insan",
    revelationType: "Medinan",
    totalVerses: 31,
    placeOfRevelation: "Medina",
  },
  {
    id: 77,
    name: "Al-Mursalat",
    revelationType: "Meccan",
    totalVerses: 50,
    placeOfRevelation: "Mecca",
  },
  {
    id: 78,
    name: "An-Naba",
    revelationType: "Meccan",
    totalVerses: 40,
    placeOfRevelation: "Mecca",
  },
  {
    id: 79,
    name: "An-Nazi'at",
    revelationType: "Meccan",
    totalVerses: 46,
    placeOfRevelation: "Mecca",
  },
  {
    id: 80,
    name: "'Abasa",
    revelationType: "Meccan",
    totalVerses: 42,
    placeOfRevelation: "Mecca",
  },
  {
    id: 81,
    name: "At-Takwir",
    revelationType: "Meccan",
    totalVerses: 29,
    placeOfRevelation: "Mecca",
  },
  {
    id: 82,
    name: "Al-Infitar",
    revelationType: "Meccan",
    totalVerses: 19,
    placeOfRevelation: "Mecca",
  },
  {
    id: 83,
    name: "Al-Mutaffifin",
    revelationType: "Meccan",
    totalVerses: 36,
    placeOfRevelation: "Mecca",
  },
  {
    id: 84,
    name: "Al-Inshiqaq",
    revelationType: "Meccan",
    totalVerses: 25,
    placeOfRevelation: "Mecca",
  },
  {
    id: 85,
    name: "Al-Buruj",
    revelationType: "Meccan",
    totalVerses: 22,
    placeOfRevelation: "Mecca",
  },
  {
    id: 86,
    name: "At-Tariq",
    revelationType: "Meccan",
    totalVerses: 17,
    placeOfRevelation: "Mecca",
  },
  {
    id: 87,
    name: "Al-A'la",
    revelationType: "Meccan",
    totalVerses: 19,
    placeOfRevelation: "Mecca",
  },
  {
    id: 88,
    name: "Al-Ghashiyah",
    revelationType: "Meccan",
    totalVerses: 26,
    placeOfRevelation: "Mecca",
  },
  {
    id: 89,
    name: "Al-Fajr",
    revelationType: "Meccan",
    totalVerses: 30,
    placeOfRevelation: "Mecca",
  },
  {
    id: 90,
    name: "Al-Balad",
    revelationType: "Meccan",
    totalVerses: 20,
    placeOfRevelation: "Mecca",
  },
  {
    id: 91,
    name: "Ash-Shams",
    revelationType: "Meccan",
    totalVerses: 15,
    placeOfRevelation: "Mecca",
  },
  {
    id: 92,
    name: "Al-Lail",
    revelationType: "Meccan",
    totalVerses: 21,
    placeOfRevelation: "Mecca",
  },
  {
    id: 93,
    name: "Ad-Duha",
    revelationType: "Meccan",
    totalVerses: 11,
    placeOfRevelation: "Mecca",
  },
  {
    id: 94,
    name: "Ash-Sharh",
    revelationType: "Meccan",
    totalVerses: 8,
    placeOfRevelation: "Mecca",
  },
  {
    id: 95,
    name: "At-Tin",
    revelationType: "Meccan",
    totalVerses: 8,
    placeOfRevelation: "Mecca",
  },
  {
    id: 96,
    name: "Al-Alaq",
    revelationType: "Meccan",
    totalVerses: 19,
    placeOfRevelation: "Mecca",
  },
  {
    id: 97,
    name: "Al-Qadr",
    revelationType: "Meccan",
    totalVerses: 5,
    placeOfRevelation: "Mecca",
  },
  {
    id: 98,
    name: "Al-Bayyinah",
    revelationType: "Medinan",
    totalVerses: 8,
    placeOfRevelation: "Medina",
  },
  {
    id: 99,
    name: "Az-Zalzalah",
    revelationType: "Meccan",
    totalVerses: 8,
    placeOfRevelation: "Mecca",
  },
  {
    id: 100,
    name: "Al-Adiyat",
    revelationType: "Meccan",
    totalVerses: 11,
    placeOfRevelation: "Mecca",
  },
  {
    id: 101,
    name: "Al-Qari'ah",
    revelationType: "Meccan",
    totalVerses: 11,
    placeOfRevelation: "Mecca",
  },
  {
    id: 102,
    name: "At-Takathur",
    revelationType: "Meccan",
    totalVerses: 8,
    placeOfRevelation: "Mecca",
  },
  {
    id: 103,
    name: "Al-Asr",
    revelationType: "Meccan",
    totalVerses: 3,
    placeOfRevelation: "Mecca",
  },
  {
    id: 104,
    name: "Al-Humazah",
    revelationType: "Meccan",
    totalVerses: 9,
    placeOfRevelation: "Mecca",
  },
  {
    id: 105,
    name: "Al-Fil",
    revelationType: "Meccan",
    totalVerses: 5,
    placeOfRevelation: "Mecca",
  },
  {
    id: 106,
    name: "Quraish",
    revelationType: "Meccan",
    totalVerses: 4,
    placeOfRevelation: "Mecca",
  },
  {
    id: 107,
    name: "Al-Ma'un",
    revelationType: "Meccan",
    totalVerses: 7,
    placeOfRevelation: "Mecca",
  },
  {
    id: 108,
    name: "Al-Kawthar",
    revelationType: "Meccan",
    totalVerses: 3,
    placeOfRevelation: "Mecca",
  },
  {
    id: 109,
    name: "Al-Kafirun",
    revelationType: "Meccan",
    totalVerses: 6,
    placeOfRevelation: "Mecca",
  },
  {
    id: 110,
    name: "An-Nasr",
    revelationType: "Medinan",
    totalVerses: 3,
    placeOfRevelation: "Medina",
  },
  {
    id: 111,
    name: "Al-Masad",
    revelationType: "Meccan",
    totalVerses: 5,
    placeOfRevelation: "Mecca",
  },
  {
    id: 112,
    name: "Al-Ikhlas",
    revelationType: "Meccan",
    totalVerses: 4,
    placeOfRevelation: "Mecca",
  },
  {
    id: 113,
    name: "Al-Falaq",
    revelationType: "Meccan",
    totalVerses: 5,
    placeOfRevelation: "Mecca",
  },
  {
    id: 114,
    name: "An-Nas",
    revelationType: "Meccan",
    totalVerses: 6,
    placeOfRevelation: "Mecca",
  },
];
